### ISSUE TITLE
Master issue for the next release

### ISSUE THREAD

**Issue by TheProjectsGuy** [TheProjectsGuy/FeatMF#1]
# About

Master issue for the next package release

## ToDo

- ~Add SIFT GPU Wrapper~ (**Couldn't find Python SIFT CUDA**)
  - Library [pypopsift](https://github.com/OpenDroneMap/pypopsift) can be found on [pypi](https://pypi.org/project/pypopsift/)
- [ ] Add Mutual Nearest Neighbor feature matching
- [ ] Add more local feature matching methods in `lfdd` (some will require downloading checkpoints and storing them)
  - [ ] ORB
  - [ ] BRISK
  - CUDA options for SIFT, other CUDA accelerated options [from OpenCV](https://docs.opencv.org/4.x/d6/d1d/group__cudafeatures2d.html)
  - [ ] [KeyNetAffNetHardNet](https://kornia.readthedocs.io/en/latest/feature.html#kornia.feature.KeyNetAffNetHardNet) as OriNet
  - [ ] R2D2
  - [ ] D2Net
  - [ ] SuperPoint
  - [ ] DeLF
  - [ ] DeLG
- [ ] Add SuperGlue matching
- [ ] Add LoFTR matching [through kornia](https://kornia.readthedocs.io/en/latest/feature.html#kornia.feature.LoFTR)
- [ ] Add multi-scale detection capabilities as an image pyramid
- [ ] Add function to stack images (side-by-side) and visualizing correspondences
- [ ] Add testing pipelines
  - OpenCV has some [sample images](https://answers.opencv.org/question/72388/where-to-get-simplejpg/) on [GitHub](https://github.com/opencv/opencv/tree/4.x/samples/data). Maybe add some in a similar manner and add [pytest](https://docs.pytest.org/) cases in [hatchling](https://hatch.pypa.io/latest/how-to/plugins/testing-builds/)
 
## Release

- [ ] Bump up the version number in all files
- [ ] Upload to PyPI using hatch
- [ ] Upload to conda
- [ ] Close this issue and open a new one
